baseURL = "/"
languageCode = "en-us"
theme = "hyde"
title = "Vandana's Blog"
disqusShortname = "vandana-vision"
[Menus]
  main = [
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/vandanakhatri/"}
  ]
[params]
googleAnalytics = ""
layoutReverse = false
theme = "hyde"
themeColor = ""
