baseURL = "/"
languageCode = "en-us"
theme = "hyde"
title = "Vandana's Blog"
disqusShortname = "vandana-vision"
[params]
description = "Articles | Research Papers | Opinions"
googleAnalytics = "UA-169289805-1"
layoutReverse = false
theme = "hyde"
themeColor = ""
