baseURL = "/"
languageCode = "en-us"
theme = "hyde"
title = "Vandana's Blog"
disqusShortname = "vandana-vision"
[params]
googleAnalytics = ""
layoutReverse = false
theme = "hyde"
themeColor = ""
theme​ = ​"​hyde​"​

[​Menus​]
  ​main​ = [
      {​Name​ = ​"​LinkedIn​"​, ​URL​ = ​"​https://www.linkedin.com/in/vandanakhatri/​"​}
  ]
