baseURL = "/"
languageCode = "en-us"
theme = "hyde"
title = "Vandana's Blog"
[params]
disqusShortname = ""
googleAnalytics = ""
layoutReverse = false
theme = "hyde"
themeColor = ""

​Menus​:
  ​main​:
    - ​Name​: ​"​LinkedIn​"​
      ​URL​: ​"​https://www.linkedin.com/in/vandanakhatri/​"
