baseURL = "/"
languageCode = "en-us"
theme = "hyde"
title = "Vandana's Blog"
disqusShortname = "vandana-vision"
[params]
description = "Articles | Research Papers"
googleAnalytics = ""
layoutReverse = false
theme = "hyde"
themeColor = ""
